// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	app "app/internal/infras/app"

	mock "github.com/stretchr/testify/mock"
)

// OptFunc is an autogenerated mock type for the OptFunc type
type OptFunc struct {
	mock.Mock
}

type OptFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *OptFunc) EXPECT() *OptFunc_Expecter {
	return &OptFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *OptFunc) Execute(_a0 *app.Opts) {
	_m.Called(_a0)
}

// OptFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type OptFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *app.Opts
func (_e *OptFunc_Expecter) Execute(_a0 interface{}) *OptFunc_Execute_Call {
	return &OptFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *OptFunc_Execute_Call) Run(run func(_a0 *app.Opts)) *OptFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*app.Opts))
	})
	return _c
}

func (_c *OptFunc_Execute_Call) Return() *OptFunc_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *OptFunc_Execute_Call) RunAndReturn(run func(*app.Opts)) *OptFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewOptFunc creates a new instance of OptFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOptFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *OptFunc {
	mock := &OptFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
