version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cake_db
    volumes:
      - cake_pgdata:/var/lib/postgresql/data
 
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  cake_pgdata:
