version: '3.8'

services:
  app:
    image: my-app:1.0.0
    container_name: my-app
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    env_file: "../.env"
    command: ["server"]
    ports:
      - 3000:${PORT}
    environment:
      PORT: ${PORT}

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: my_db
    volumes:
      - my_pgdata:/var/lib/postgresql/data
 
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  my_pgdata:
